### ISSUE TITLE
Requirements for the input tree?

### ISSUE THREAD

**Issue by maesaar** [ansariazim/treeBreaker#6]
Is there some requirements for the input tree? 

FIRST:
Is it important to use whole-genome alignment or is core genome alignment also suitable for tree generation?

SECOND:
What tree would be best to use as an input:
1) wgMLST core genome tree (with recombination)?
2) The same tree but with corrected recombination eg ClonalFrameML output tree?
3) Output tree from BactDating using CFML tree as input?

Thank you for the clarifications

**Comment by maesaar** [comment]
As I understand from the manuscript unrecombined core genome is suitable to use. But question still remains is it ok to use CFML output tree or BactDating output tree?

The manuscript said phenotypic trait was used, but would it also work with genotypic trait (coded 1,0)?

Thank you again

**Comment by ansariazim** [comment]
Hi there,

FIRST: The method does not depend on how you have generated the tree, it works on any kind of tree. What kind of tree you should use and does it make sense depends on the questions that you are asking.


SECOND: Again this depends on the question that you are asking. The method does not assume anything about how the tree was generated. It assumes that the tree is the correct tree for your question. So you could potentially use all of those trees, You need to think about what tree answers the questions that you are asking.

Best.
Azim

**Comment by ansariazim** [comment]
Hi there,

Yes, you can use genotypic trait or any other trait. It will find branches where the trait distribution has changed relative to the rest of the tree.

Best.
Azim

P.S. If you want to use treeBreaker, please use the version with the last commits from 2016. the R version does not seem to install properly for people. So you need to use the command line version from 2016.

**Comment by maesaar** [comment]
Thank you for thorough answer. 

I am currently trying to use treeBreaker using virulence and amr genes with dated unrecombined core genome tree to see when did these genes emerge. 

Would it be better if genotypic trait (eg gene/mutation) is present in alignment what would be used for tree generation or not?

Thanks

**Comment by ansariazim** [comment]
Hi there,

I would say if you are using core genome, then including a gene or two in your alignment is not going to change the tree much at all. So it probably is not going to make any difference if you include them or not in practice. 

In principle if the tree is supposed to capture the clonal genealogy between the isolates, then the question would be do you think including the gene that you are interested in, improve or weaken the clonal genealogy inference?

Sorry, I cannot give you a definite answer, as I am not familiar with your data. But in practice I would say it is not going to make that much difference if you include them or not.

Best.
Azim

**Comment by mmaesaar** [comment]
I compiled treeBreaker but it gives me error (using with test data).

```
./treeBreaker -x 1000 -y 1000 -z 100 testTree.newick phenoTestFile.txt output
Syntax error.
        Usage: treeBreaker [OPTIONS] inputfile_tree inputfile_phenotype outputfile
        
        Options:
        -x NUM      Sets the number of iterations after burn-in (default is 500000)
        -y NUM      Sets the number of burn-in iterations (default is 500000)
        -z NUM      Sets the number of iterations between samples (default is 1000)
        -S NUM      Sets the seed for the random number generator to NUM
        -v          Verbose mode
```

**Comment by iqbal-lab** [comment]
That last comment is a different bug, and should be a different bug report.
